#!/bin/bash

tokens=(LEFT_PAREN RIGHT_PAREN LEFT_BRACE RIGHT_BRACE COMMA DOT MINUS PLUS PLUS_PLUS MINUS_MINUS CARET SEMICOLON SLASH STAR BANG BANG_EQUAL EQUAL EQUAL_EQUAL GREATER GREATER_EQUAL LESS LESS_EQUAL IDENTIFIER STRING NUMBER AND CLASS ELSE FALSE FOR FUN IF NIL OR PRINT RETURN SUPER THIS TRUE VAR WHILE ERROR EOF)

for t in ${tokens[*]}; do
    printf "    %-24s = {NULL,     NULL,   PREC_NONE},\n" "[TOKEN_${t}]"
done
