#ifndef NATIVE_H
#define NATIVE_H

/* Injected dependencies from native_includes.h.in */
#include "value.h"
#include "object.h"
//#include "table.h"
//#include "vm.h"

// Automatically extracted signatures
void defineNativeClassConstant(ObjClass* klass, const char* name, Value value);
Value clockNative(int argCount, Value* args);
Value strNative(int argCount, Value* args);
Value typeofNative(int argCount, Value* args);
Value chrNative(int argCount, Value* args);
Value evalNative(int argCount, Value* args);
Value createInstanceNative(int argCount, Value* args);
Value programNative(int argCount, Value* args);
Value isNumberNative(int argCount, Value* args);
Value isStringNative(int argCount, Value* args);
Value isBoolNative(int argCount, Value* args);
Value isNilNative(int argCount, Value* args);
Value isClassNative(int argCount, Value* args);
Value isInstanceNative(int argCount, Value* args);
Value listFieldsNative(int argCount, Value* args);
Value getFieldNative(int argCount, Value* args);
Value setFieldNative(int argCount, Value* args);
Value getMethodsNative(int argCount, Value* args);
Value hasMethodNative(int argCount, Value* args);
Value getSuperclassNative(int argCount, Value* args);
Value objectToStringNative(int argCount, Value* args);
Value objectClassMethod(int argCount, Value* args);
Value objectClassNameMethod(int argCount, Value* args);
Value objectFreezeNative(int argCount, Value* args);
Value objectIsfrozenNative(int argCount, Value* args);
void initCoreLibrary();
Value stringTrimNative(int argCount, Value* args);
Value stringContainsNative(int argCount, Value* args);
Value stringFindNative(int argCount, Value* args);
Value stringToUpperNative(int argCount, Value* args);
Value stringToLowerNative(int argCount, Value* args);
Value stringLenNative(int argCount, Value* args);
Value stringSplitNative(int argCount, Value* args);
Value stringSliceNative(int argCount, Value* args);
Value stringToarrayNative(int argCount, Value* args);
Value stringTokensNative(int argCount, Value* args);
Value stringFormatNative(int argCount, Value* args);
void initStringClass();
Value mapNativeConstructor(int argCount, Value* args);
Value mapKeysNative(int argCount, Value* args);
Value mapValuesNative(int argCount, Value* args);
Value mapHasNative(int argCount, Value* args);
Value mapRemoveNative(int argCount, Value* args);
Value mapLenNative(int argCount, Value* args);
Value mapEachNative(int argCount, Value* args);
void initMapClass();
Value setNativeConstructor(int argCount, Value* args);
Value setAddNative(int argCount, Value* args);
void setRemove(ObjSet* set, Value val);
Value setCountNative(int argCount, Value* args);
Value setRemoveNative(int argCount, Value* args);
Value setHasNative(int argCount, Value* args);
Value setLengthNative(int argCount, Value* args);
Value setMultisetNative(int argCount, Value* args);
Value setKeysNative(int argCount, Value* args);
Value setToMapNative(int argCount, Value* args);
void initSetClass();
Value mathSqrtNative(int argCount, Value* args);
Value mathAbsNative(int argCount, Value* args);
Value mathFloorNative(int argCount, Value* args);
Value mathCeilNative(int argCount, Value* args);
Value mathRandomNative(int argCount, Value* args);
Value mathExpNative(int argCount, Value* args);
Value hexNative(int argCount, Value* args);
Value octNative(int argCount, Value* args);
Value binNative(int argCount, Value* args);
Value bitTestNative(int argCount, Value* args);
Value mathMinNative(int argCount, Value* args);
Value mathMaxNative(int argCount, Value* args);
Value mathParseNative(int argCount, Value* args);
Value fromHexNative(int argCount, Value* args);
Value fromBinNative(int argCount, Value* args);
Value mathRoundNative(int argCount, Value* args);
Value toNumberNative(int argCount, Value* args);
Value mathSinNative(int argCount, Value* args);
Value mathTanNative(int argCount, Value* args);
Value mathAtan2Native(int argCount, Value* args);
Value mathCosNative(int argCount, Value* args);
Value mathAcosNative(int argCount, Value* args);
Value numberToIntNative(int argCount, Value* args);
Value numberToFixedNative(int argCount, Value* args);
Value numberToStringNative(int argCount, Value* args);
void initMathLibrary();
Value arrayPushNative(int argCount, Value* args);
Value arrayPopNative(int argCount, Value* args);
Value arrayLenNative(int argCount, Value* args);
Value arrayMapNative(int argCount, Value* args);
Value arrayDupNative(int argCount, Value* args);
Value arrayIsEmptyNative(int argCount, Value* args);
Value arrayFilterNative(int argCount, Value* args);
Value arrayReduceNative(int argCount, Value* args);
Value arrayJoinNative(int argCount, Value* args);
Value arrayEachNative(int argCount, Value* args);
Value arrayFindNative(int argCount, Value* args);
Value arrayHasNative(int argCount, Value* args);
Value arraySliceNative(int argCount, Value* args);
Value arraySortNative(int argCount, Value* args);
Value arraySortSliceNative(int argCount, Value* args);
Value arrayReverseNative(int argCount, Value* args);
Value arrayFlattenNative(int argCount, Value* args);
Value arrayStringNative(int argCount, Value* args);
Value arrayFirstNative(int argCount, Value* args);
Value arrayRestNative(int argCount, Value* args);
Value arraySplitNative(int argCount, Value* args);
void debugPrintArrayMethods();
Value arrayNativeConstructor(int argCount, Value* args);
void initArrayClass();
Value resultNativeConstructor(int argCount, Value* args);
Value resultUnwrapNative(int argCount, Value* args);
Value resultUnwrapOrNative(int argCount, Value* args);
Value optionNativeConstructor(int argCount, Value* args);
Value optionUnwrapNative(int argCount, Value* args);
Value optionUnwrapOrNative(int argCount, Value* args);
void initResultAndOptionClass();
Value regexNativeConstructor(int argCount, Value* args);
Value regexTestNative(int argCount, Value* args);
Value regexMatchNative(int argCount, Value* args);
Value regexGetPatternNative(int argCount, Value* args);
void regexDestructor(ObjInstance* inst);
void initRegexClass();
void closeFileInternal(ObjInstance* inst);
void fileDestructor(ObjInstance* inst);
Value fileLoadNative(int argCount, Value* args);
Value fileSaveNative(int argCount, Value* args);
Value fileExistsNative(int argCount, Value* args);
Value fileListNative(int argCount, Value* args);
Value fileOpenNative(int argCount, Value* args);
Value fileReadNative(int argCount, Value* args);
Value fileReadlineNative(int argCount, Value* args);
Value fileWriteNative(int argCount, Value* args);
Value fileCloseNative(int argCount, Value* args);
Value fileSeekNative(int argCount, Value* args);
Value fileTellNative(int argCount, Value* args);
Value fileStderrNative(int argCount, Value* args);
Value fileFlushNative(int argCount, Value* args);
Value fileMkdirNative(int argCount, Value* args);
void initFileLibrary();
Value processRunStatic(int argCount, Value* args);
Value processCaptureStatic(int argCount, Value* args);
Value processForkStatic(int argCount, Value* args);
char* valueToCString(Value val);
Value processExecStatic(int argCount, Value* args);
Value processPidStatic(int argCount, Value* args);
Value processWaitStatic(int argCount, Value* args);
Value processPipeStatic(int argCount, Value* args);
Value processReadStatic(int argCount, Value* args);
Value processCloseStatic(int argCount, Value* args);
Value processWriteStatic(int argCount, Value* args);
void initProcessClass();
Value structPackNative(int argCount, Value* args);
Value structUnpackNative(int argCount, Value* args);
void initStructClass();
Value hgfGCNative(int argCount, Value* args);
Value get_hgfGCNative(int argCount, Value* args);
Value thresholdGCNative(int argCount, Value* args);
Value get_thresholdGCNative(int argCount, Value* args);
Value bumpsizeGCNative(int argCount, Value* args);
Value get_bumpsizeGCNative(int argCount, Value* args);
Value stressmodeGCNative(int argCount, Value* args);
Value get_stressmodeGCNative(int argCount, Value* args);
Value typeGCNative(int argCount, Value* args);
Value get_typeGCNative(int argCount, Value* args);
Value systemGCNative(int argCount, Value* args);
Value gcStatsNative(int argCount, Value* args);
void initGCLibrary();
void ioDestructor(ObjInstance* inst);
Value ioCallHandler(int argCount, Value* args);
Value ioTcpNative(int argCount, Value* args);
Value ioInspectNative(int argCount, Value* args);
Value ioConnectNative(int argCount, Value* args);
Value ioSendNative(int argCount, Value* args);
Value ioRecvNative(int argCount, Value* args);
Value ioListenNative(int argCount, Value* args);
Value ioAcceptNative(int argCount, Value* args);
Value ioBindNative(int argCount, Value* args);
Value ioReadableNative(int argCount, Value* args);
Value ioCloseNative(int argCount, Value* args);
Value ioPollNative(int argCount, Value* args);
Value ioSetRecvTimeoutNative(int argCount, Value* args);
void initIOClass();
Value systemTimeNative(int argCount, Value* args);
Value systemExitNative(int argCount, Value* args);
Value systemMemNative(int argCount, Value* args);
Value systemResetStackNative(int argCount, Value* args);
Value systemShowStackNative(int argCount, Value* args);
Value systemSetPrecisionNative(int argCount, Value* args);
Value systemSetNotationNative(int argCount, Value* args);
Value systemDebugPrintNative(int argCount, Value* args);
Value systemTraceNative(int argCount, Value* args);
Value systemStrictNative(int argCount, Value* args);
Value systemWarnNative(int argCount, Value* args);
Value systemSleepNative(int argCount, Value* args);
void initSystemLibrary(int argc, const char* argv[], const char* env[]);

#endif // NATIVE_H
